name: human-text
version: 0.1.0.0
category: Text

library:
  source-dirs: src
  exposed-modules:
    - Data.Text.Human

dependencies:
  - base
  - text

ghc-options:
  - -Wall

default-extensions:
  - NoImplicitPrelude
