name: human-text
version: 0.1.0.0
category: Text

synopsis: >
  A lawless typeclass for converting values to human-friendly text.

description: >
  It's embarrassing when details of a programming language leak into a user
  interface; use the 'humanText' function instead of 'show' to display text
  to people.

author:     Chris Martin <ch.martin@gmail.com>
maintainer: Chris Martin <ch.martin@gmail.com>

license:      Apache-2.0
license-file: license.txt

library:
  source-dirs: src
  exposed-modules:
    - Data.Text.Human

dependencies:
  - base
  - text

ghc-options:
  - -Wall

default-extensions:
  - NoImplicitPrelude
