name: accumulate

library:
  source-dirs: src
  exposed-modules:
    - Control.Applicative.Accumulate

dependencies:
  - base
  - safe-exceptions

ghc-options:
  - -Wall

default-extensions:
  - NoImplicitPrelude
