resolver: lts-8.8

packages:
  - accumulate
  - atomic-modify
  - decimal-text
  - elephant
  - encodings
  - exception-records
  - human-parse
  - human-text
  - irs-forms
  - mvar-lock
  - tchan-log-demo

nix:
  shell-file: shell.nix
